# Generated by Django 4.1.3 on 2022-12-29 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_modelname_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelname',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
