# Generated by Django 4.1.3 on 2022-12-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_modelname_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelname',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
